"""Hypothesis scaffolder — Layer 4, gen tier (§9.1 of the plan).

Deterministic: for each changed public function that no test references,
emit an info finding and write a property-test *scaffold* (never
auto-committed, never under tests/) to ``.gauntlet/scaffolds/``. Scaffolds
are suggestions for the agent/human test-author round.
"""

from __future__ import annotations

import ast
import re
from dataclasses import dataclass
from pathlib import Path

from gauntlet.findings import Action, Finding, Layer, Severity, make_id
from gauntlet.runners import RunContext

SCAFFOLD_DIR = Path(".gauntlet") / "scaffolds"

#: Type-hint name → hypothesis strategy expression (§9.1).
STRATEGY_MAP = {
    "int": "st.integers()",
    "float": "st.floats(allow_nan=False)",
    "str": "st.text()",
    "bool": "st.booleans()",
    "bytes": "st.binary()",
}


@dataclass
class PublicFunction:
    """A changed public function eligible for property scaffolding."""

    file: Path
    qualname: str
    name: str
    line: int
    params: list[tuple[str, str | None]]  # (name, annotation source or None)


def _annotation_name(node: ast.expr | None) -> str | None:
    if node is None:
        return None
    try:
        return ast.unparse(node)
    except Exception:  # noqa: BLE001 - annotation rendering is best-effort
        return None


def collect_public_functions(root: Path, files: list[Path]) -> list[PublicFunction]:
    """Module-level defs and class methods without a leading underscore."""
    functions: list[PublicFunction] = []
    for file in files:
        try:
            tree = ast.parse((root / file).read_text(errors="replace"))
        except SyntaxError:
            continue
        for node in tree.body:
            if isinstance(node, ast.FunctionDef) and not node.name.startswith("_"):
                functions.append(_to_public_function(file, node, node.name))
            elif isinstance(node, ast.ClassDef):
                for member in node.body:
                    if isinstance(
                        member, ast.FunctionDef
                    ) and not member.name.startswith("_"):
                        functions.append(
                            _to_public_function(
                                file, member, f"{node.name}.{member.name}"
                            )
                        )
    return functions


def _to_public_function(
    file: Path, node: ast.FunctionDef, qualname: str
) -> PublicFunction:
    params = [
        (arg.arg, _annotation_name(arg.annotation))
        for arg in node.args.args
        if arg.arg not in ("self", "cls")
    ]
    return PublicFunction(
        file=file, qualname=qualname, name=node.name, line=node.lineno, params=params
    )


def tested_names(root: Path, test_paths: list[str]) -> set[str]:
    """Every word appearing in the repo's test files (name-reference check)."""
    words: set[str] = set()
    for entry in test_paths:
        base = root / entry
        candidates = (
            [base]
            if base.is_file()
            else list(base.rglob("*.py"))
            if base.is_dir()
            else []
        )
        for path in candidates:
            try:
                words.update(re.findall(r"\w+", path.read_text(errors="replace")))
            except OSError:
                continue
    return words


def module_import_path(file: Path, src_paths: list[str]) -> str:
    """Import path for a repo-relative .py file (src-layout aware)."""
    parts = file.with_suffix("").parts
    for src in src_paths:
        src_parts = Path(src).parts
        if parts[: len(src_parts)] == src_parts:
            parts = parts[len(src_parts) :]
            break
    return ".".join(parts)


def strategy_for(annotation: str | None) -> tuple[str, bool]:
    """(strategy expression, known?) for a parameter annotation."""
    if annotation in STRATEGY_MAP:
        return STRATEGY_MAP[annotation], True
    return "st.nothing()", False


def render_scaffold(module: str, functions: list[PublicFunction]) -> str:
    """The scaffold file content for one module."""
    lines = [
        '"""Hypothesis property scaffolds generated by gauntlet (gen tier).',
        "",
        "Suggestions only: move what is useful into tests/ (they must run, pass,",
        "and strictly increase diff coverage) and delete the rest. Never asserted",
        "on implementation internals.",
        '"""',
        "",
        "from hypothesis import given",
        "from hypothesis import strategies as st",
        "",
        f"from {module} import {', '.join(sorted({f.name for f in functions}))}",
        "",
    ]
    for func in functions:
        given_args = []
        todo_params = []
        for param, annotation in func.params:
            strategy, known = strategy_for(annotation)
            given_args.append(f"{param}={strategy}")
            if not known:
                todo_params.append(param)
        lines += ["", f"@given({', '.join(given_args)})"]
        signature_params = ", ".join(name for name, _ in func.params)
        lines.append(f"def test_{func.name}_properties({signature_params}) -> None:")
        if todo_params:
            lines.append(
                f"    # TODO: pick real strategies for: {', '.join(todo_params)}"
            )
        call_args = ", ".join(name for name, _ in func.params)
        lines += [
            f"    result = {func.name}({call_args})",
            "    # TODO: assert real properties/invariants — round-trips,",
            "    # idempotence, ordering, bounds — not just non-None.",
            "    assert result is not None",
        ]
    return "\n".join(lines) + "\n"


class HypothesisGenRunner:
    """Scaffolds property tests for untested changed public functions."""

    name = "hypothesis-gen"
    layer = Layer.TEST_GEN
    tier = "gen"

    def __init__(self, ctx: RunContext) -> None:
        self.ctx = ctx

    def available(self) -> bool:
        """Always available: pure ast + file writes under .gauntlet/."""
        return True

    def run(self, ctx: RunContext) -> list[Finding]:
        """Emit untested-function findings and write scaffolds."""
        src_files = [
            f
            for f in ctx.changed_py_files
            if not any(
                f == Path(t) or f.is_relative_to(t) for t in ctx.config.test_paths
            )
        ]
        if not src_files:
            return []
        functions = collect_public_functions(ctx.root, src_files)
        known_words = tested_names(ctx.root, ctx.config.test_paths)
        untested = [f for f in functions if f.name not in known_words]
        if not untested:
            return []

        findings: list[Finding] = []
        by_module: dict[Path, list[PublicFunction]] = {}
        for func in untested:
            by_module.setdefault(func.file, []).append(func)
            findings.append(
                Finding(
                    id=make_id(self.name, "untested", str(func.file), func.qualname),
                    layer=self.layer,
                    tool=self.name,
                    severity=Severity.INFO,
                    action=Action.NO_OP,
                    file=str(func.file),
                    line=func.line,
                    message=(
                        f"public function '{func.qualname}' has no test referencing "
                        "it — property scaffold written"
                    ),
                    fix_hint="see .gauntlet/scaffolds/ for a Hypothesis skeleton",
                )
            )

        scaffold_dir = ctx.root / SCAFFOLD_DIR
        scaffold_dir.mkdir(parents=True, exist_ok=True)
        for file, funcs in sorted(by_module.items()):
            module = module_import_path(file, ctx.config.src_paths)
            scaffold = scaffold_dir / f"test_{file.stem}_props.py"
            scaffold.write_text(render_scaffold(module, funcs))
            findings.append(
                Finding(
                    id=make_id(self.name, "scaffold", str(file)),
                    layer=self.layer,
                    tool=self.name,
                    severity=Severity.INFO,
                    action=Action.NO_OP,
                    file=str(SCAFFOLD_DIR / scaffold.name),
                    line=0,
                    message=(
                        f"scaffold for {module}: {', '.join(f.qualname for f in funcs)}"
                    ),
                )
            )
        return findings
